# Preprocessing

#### Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

## Exploring the data

### About dataset
This dataset provides a comprehensive collection of attributes for various animal species worldwide. It includes detailed information such as Animal name, Height, Weight, Color, Lifespan, Diet, Habitat, Predators, Average and Top Speed, Countries Found, Conservation Status, Family, Gestation Period, Social Structure, and Offspring per Birth. These data points allow researchers and enthusiasts to analyze animal characteristics, study habitats and behaviors, explore dietary patterns, assess conservation statuses, and conduct ecological and wildlife studies effectively.

The primary task associated with this dataset involves data cleaning and classification of animals into three categories based on their diet: Omnivore, Carnivore, and Herbivore.

#### Dataset Glossary (Column-wise)
- Animal - Name of the animal.
- Height (cm) - Height range in centimeters for the animal.
- Weight (kg) - Weight range in kilograms for the animal.
- Color - Common colors associated with the animal's appearance.
- Lifespan (years) - Average lifespan of the animal in years.
- Diet - Type of diet the animal primarily follows (e.g., Carnivore, Herbivore).
- Habitat - Typical habitat or environment where the animal is found.
- Predators - Natural enemies or organisms that prey on the animal.
- Average Speed (km/h) - The average speed range the animal can achieve in kilometers per hour.
- Countries Found - Countries or regions where the animal is commonly found.
- Conservation Status - The conservation status of the animal as per relevant conservation organizations.
- Family - Taxonomic family the animal belongs to.
- Gestation Period (days) - Range of days representing the gestation or pregnancy period of the animal.
- Top Speed (km/h) - The maximum speed the animal can achieve in kilometers per hour.
- Social Structure - Information about the social behavior or structure of the animal (e.g., Solitary, Group-based).
- Offspring per Birth - The typical number of offspring born per birth or reproduction event for the animal.

In [2]:
df = pd.read_csv('data/Animal Dataset.csv')
df.head()

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

Instances of 'Not Applicable' and 'Varies' appear in the data; substituting them with NaN will improve handling of missing values.

In [4]:
df = df.replace('Not Applicable',np.nan)
df = df.replace('Varies',np.nan)

df.isnull().sum()

Animal                      0
Height (cm)                 3
Weight (kg)                 3
Color                       5
Lifespan (years)            6
Diet                        0
Habitat                     1
Predators                  14
Average Speed (km/h)       26
Countries Found             0
Conservation Status        12
Family                      0
Gestation Period (days)    19
Top Speed (km/h)           38
Social Structure            1
Offspring per Birth        25
dtype: int64

There are 153 NaN values in the data that need to be addressed.

In [5]:
df.isnull().sum().sum()

153

Additionally, there are some duplicate data entries that need to be addressed.

In [6]:
df[df.duplicated(subset='Animal', keep=False)]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
28,Blobfish,Up to 30,Up to 10,Pinkish-gray,Up to 100,Carnivore,Deep-sea,NaN,NaN,"Australia, New Zealand, Tasmania",Vulnerable,Psychrolutidae,NaN,NaN,Solitary,NaN
29,Blobfish,NaN,NaN,Pinkish-gray,Up to 130,Carnivore,Deep-sea,NaN,NaN,Deep-sea regions,Vulnerable,Psychrolutidae,NaN,NaN,Solitary,NaN
77,Goblin Shark,Up to 320,Up to 210,Pinkish-gray,30-35,Carnivore,Deep-sea,"Larger Fish, Other Sharks",1.6-3,Worldwide,Data Deficient,Mitsukurinidae,NaN,NaN,Solitary,NaN
78,Goblin Shark,Up to 366,Up to 210,Pinkish-gray,30-35,Carnivore,Deep-sea,NaN,NaN,Worldwide,Data Deficient,Mitsukurinidae,NaN,NaN,Solitary,NaN
81,Great White Shark,Up to 610,Up to 2268,Grey,30-40,Carnivore,Oceans,Orcas,56,Oceans worldwide,Vulnerable,Lamnidae,12-18 months,56,Solitary,2-14 (approx.)
82,Great White Shark,Up to 670,Up to 2268,"Gray, White",70,Carnivore,Oceans,Orcas,56,Worldwide,Vulnerable,Lamnidae,12-18,56,Solitary,2-17
84,Green Sea Turtle,Up to 120,Up to 200,Greenish-brown,80-100,Herbivore,"Oceans, Coastal Areas",Predatory Fish,1.6-3.2,Oceans worldwide,Endangered,Cheloniidae,45-70,35,Solitary,NaN
85,Green Sea Turtle,70-120,68-190,Green,80,Herbivore,Oceans,"Sharks, Orcas",35,Worldwide,Endangered,Cheloniidae,45-75,35,Solitary,NaN
87,Hagfish,Up to 127,Up to 0.7,"Pink, Gray",Up to 300,Scavenger,"Ocean Floor, Deep-sea",Various Predators,0.8,Oceans worldwide,Least Concern,Myxinidae,NaN,NaN,Solitary,NaN
88,Hagfish,Up to 127,Up to 0.6,Pinkish-gray,Up to 30,Carnivore,Deep-sea,NaN,NaN,Worldwide,Data Deficient,Myxinidae,NaN,NaN,Solitary,NaN
106,Lemur,30-50,0.6-3.5,Various,15-25,Omnivore,"Rainforests, Madagascar","Fossa, Hawks",24-29,Madagascar,Vulnerable,Lemuridae,134-138,29,Group-based,1-2
107,Lemur,30-65,0.6-4.5,NaN,15-25,Herbivore,Forests,Fossa,29,Madagascar,Critically Endangered,Lemuridae,120-135,29,Group-based,1
109,Lyrebird,80-100,0.9-1.2,"Brown, Black",15-20,Omnivore,Rainforests,"Birds of Prey, Dingoes",0.02-0.03,Australia,Least Concern,Menuridae,50-55,NaN,Solitary,1
110,Lyrebird,77-100,0.85-1.1,"Brown, Grey",Up to 20,Omnivore,Forests,Birds of Prey,NaN,Australia,Least Concern,Menuridae,50-55,NaN,Solitary,1
124,Okapi,200-250,200-350,"Brown, White",20-30,Herbivore,Central Africa,"Leopards, Lions",56,Democratic Republic of Congo,Endangered,Giraffidae,440-450,58,Solitary,1
125,Okapi,200-250,200-350,"Dark Brown, White",20-30,Herbivore,Rainforests,"Leopards, Humans",58,Democratic Republic of Congo,Endangered,Giraffidae,420-450,58,Solitary,1
130,Pink Fairy Armadillo,9-15,Up to 120,Pink,4-8,Insectivore,Grasslands,"Foxes, Birds of Prey",NaN,Argentina,Near Threatened,Chlamyphoridae,60-64,NaN,Solitary,1
131,Pink Fairy Armadillo,12-15,Up to 0.1,Pinkish,4,Insectivore,Grasslands,"Birds, Canids",0.8,Argentina,Near Threatened,Dasypodidae,60-64,0.8,Solitary,1

Unique values in each column indicate a need for heavy data cleaning.

In [7]:
for i in df.columns[1:]:
    print(i, df[i].unique(), end='\n\n')

Height (cm) ['105-130' '40-50' '270-310' '80-110' '75-80' '67-101' '2-13' '152-186'
 '52-91' '140-160' '70-90' '25-30' 'Up to 120' '200-300' '200-250'
 '112-160' 'Up to 30' '35-37' '76-107' '70-102' '41-71' 'Up to 75'
 'Up to 1100' 'Up to 60' '35-40' '90-110' '132-180' nan '22-30' 'Up to 15'
 'Up to 33.5m' '81-85' 'Up to 20' 'Up to 150' '96-150' '200-400' '53-63'
 'Up to 5' '70-120' 'Up to 460' '50-62' 'Up to 160' 'Up to 180' '7-10'
 'Up to 200' '20-36' '50-61' '50-55' '48-58' 'Up to 300' '140-188' '30-45'
 'Up to 270' '100' '23-26' '14-30' '20-40' '15-25' 'Up to 40' 'Up to 90'
 '49-53' '48-53' 'Up to 183' '180-300' '80-105' 'Up to 600' '2.2-7.7'
 'Up to 320' 'Up to 366' 'Up to 35' '3-6' 'Up to 610' 'Up to 670'
 'Up to 550' '130-160' 'Up to 127' '86-107' '120-160' 'Up to 56' '7.5-13'
 'Up to 1700' '60-70' 'Up to 70' '35-55' '50-60' '7-15' '25-46' 'Up to 25'
 '30-50' '30-65' '45-60' '80-100' '77-100' '300-400' '67-107' 'Up to 115'
 '25-35' 'Up to 244' '120-200' 'Up to 9' 'Up to 500' '35-45' '30-100'
 '45-75' 'Up to 18' '9-15' '12-15' '10-15' '21-58' '81-104' '40-54'
 '35-50' '140-180' '50-65' '5.1-7.5' '56-69' '100-150' '54-62' '110-140'
 'Up to 394' '20-38' '50-70' '52-71' 'Up to 2056' '35-64' '70-92' '12-20'
 '66-100' '100-145' '112-145' '70-87' '120-150' 'Up to 16' '30-76'
 '100-130' 'Up to 0.5' '46-58' '61-78' '108-133' 'Up to 1440' '55-65'
 '51-79' 'Up to 0.7' 'Up to 80' '35-41' '46-56' 'Up to 3200' '85-150'
 '140-200' 'Up to 1800' '1400-2300' '240-260' '65-100' '170-250' '66-81'
 '84-118' '6.7-18' 'Up to 4200' '60-65' '220-340' 'Up to 330']

Weight (kg) ['40-65' '8-14' '2700-6000' '120-250' '18-36' '19-120' 'Up to 0.5'
 '318-1,000' '22-41' '380-1000' '65-90' '2.5-9' 'Up to 6.7' '2000-5000'
 '500-620' '120-140' '18-40' 'Up to 300' '2.2-2.7' '150-400' '3-6' '2-5'
 '5-13' '400-700' 'Up to 600' '2.5-4' '220-260' '800-1,400' 'Up to 10' nan
 '0.07-0.12' 'Up to 0.028' 'Up to 200 tons' '1.5-3' 'Up to 0.3' '30-40'
 '30-82' '150-650' '25-32' 'Up to 0.006' '70-780' 'Up to 90' '35-66'
 '20-72' '26-70' 'Up to 65' '50-300' '100-135' '4.5-16' '23-32' '12-21'
 '13-20' 'Up to 420' '73-204' '2.5-6.5' 'Up to 20' '22-45' '300-400'
 '0.6-1.2' '0.8-1.6' 'Up to 55' 'Up to 1.1' '5-8' '1.5-2.5' '1.7-2.6'
 'Up to 417' '600-1300' '28-52' 'Up to 1500' 'Up to 25' '70-125'
 'Up to 2.3' 'Up to 0.03' 'Up to 210' 'Up to 0.7' 'Up to 2.4' 'Up to 2268'
 'Up to 97.5' 'Up to 200' '68-190' '350-450' 'Up to 0.6' 'Up to 160'
 '4.5-9' '1300-3200' '2-20' 'Up to 30000' '9-14' 'Up to 6' '10-14'
 'Up to 4' '0.035-0.15' 'Up to 9' '1.0-3.3' 'Up to 250' '0.6-3.5'
 '0.6-4.5' '2.5-10' '0.9-1.2' '0.85-1.1' 'Up to 2.2' '400-590' '20-25'
 'Up to 2.7' 'Up to 110' '0.6-1' 'Up to 166' '70-200' 'Up to 80'
 'Up to 1600' 'Up to 1' '0.32-1' '200-350' '2-40' '5.5-16' 'Up to 0.4'
 'Up to 120' 'Up to 0.1' '0.7-2.4' 'Up to 700' '0.2-1' '0.02-0.5' '14-24'
 '40-70' 'Up to 0.8' '2.5-5' '3-7' '18-95' '36-60' 'Up to 100' '2.3-4.5'
 '8-18' '4-6' 'Up to 800' '16-27' '3.6-9' '0.3-1.6' '22-75' '1.6-3.3'
 '35-77' 'Up to 57000' '6-9' '44-64' '0.5-1' 'Up to 0.06' '23-56'
 '750-950' '500-950' '47-121' '27-80' 'Up to 0.2' '4-14' '20-30'
 'Up to 0.02' 'Up to 85' 'Up to 8' '63-75' '100-390' 'Up to 24950'
 '540-700' '4-8' 'Up to 1.5' '0.4-1' '2-3' 'Up to 0.05' 'Up to 1200'
 '60-150' '300-1200' '68-182' '68-181' '1800-2500' '100-300' '30-120'
 '200-390' '23-80' '9-25' '20-35' '0.02-0.07' 'Up to 12000' '500-1200'
 '1-3' '400-900' 'Up to 32']

Color ['Grey' 'Yellow-brown' 'Tan' 'Multicolored' 'Brown' 'Various'
 'Brown, White' 'White' 'Silver, Gold, Green' 'Black, White' 'Gray, White'
 'Brown, Gray' 'Black, Brown' 'Brown, Black' 'Brown, Black, White'
 'Gray, Brown' 'Yellowish-gray' 'Orange, Black' 'Gray, Black'
 'Pinkish-gray' 'Blue, White' 'Blue' 'Blue-grey' 'Blue, Brown' 'Black'
 'Reddish-brown' 'Fawn, Brindle' 'Tan with Black Spots' 'Dark Brown'
 'Orange' 'Brown, Grey' 'Gray, Yellow' 'White, Black' 'Red, Brown'
 'Tan, Brown' 'Gray' 'Brown, Tan' 'Grayish-brown' 'Brown, Spiny' 'Cream'
 'Black, Yellow' 'Brown, Reddish-brown' nan 'Dark Brown, Black'
 'Brownish-gray' 'Black, Orange' 'Green, Transparent'
 'Golden, Reddish-brown' 'Olive-green' 'Greenish-brown' 'Green'
 'Pink, Gray' 'Silver, Gray' 'Yellowish-brown' 'Yellow, Black'
 'Brown, Green' 'Reddish-Brown' 'Pink, Wrinkled' 'Gray, Mottled White'
 'Red, White' 'Dark Brown, White' 'Brown, Yellowish' 'Pink' 'Pinkish'
 'Orange, Brown' 'Brown, Red' 'Green, Red' 'Black, Tan' 'Black, Grey'
 'Yellowish-Tan, Black' 'Metallic Blue' 'Yellowish-Brown'
 'Grayish-yellow, Black' 'Yellowish-Orange, Black' 'Black, Pink'
 'Orange, Black Stripes' 'Black, Brown, Gray' 'Black, Orange, Yellow'
 'Bald, Red' 'Grey, White' 'Dark Gray' 'White, Black Stripes'
 'Brown, Shaggy' 'Yellow, White' 'White, Hairy']

Lifespan (years) ['20-30' '10-12' '60-70' '10-14' '15-20' '4-17' '25-30' '10-20' '3-6'
 '60-80' '20-25' '14-17' '10-15' '20-23' '7-10' 'Up to 30' '6-15' '6-8'
 '35-50' 'Up to 100' 'Up to 130' '1-2 weeks' '70-90' '12-17' '6-8 months'
 '40-60' '35-45' '20-50' '1-2' '8-10' '40-50' 'Up to 70' '6-10' 'Up to 60'
 '30-50' '15-18' '10-13' '70-80' '2-5' '15-23' 'Up to 15' '100-150' nan
 '3-5' 'Up to 20' '10-14 days' '30-35' '10-17' '30-40' '70' '80-100' '80'
 'Up to 300' '20-35' '25-35' 'Up to 20 years' '45-50' '60+' '25-50'
 'Up to 10' '15-25' '20-40' '12-14' '35-40' 'Up to 32' '50-60' 'Up to 5'
 '30-45' '5-10' '4-8' '4' '6-12' '3-10' 'Up to 23' '8-12' 'Up to 21'
 '28-35' '10-16' '20-24' '10-25' '25-36' '12-25' 'Up to 4' '12-20' '5-8'
 '4-7' '5-20' '10' 'Up to 28' '20-21' '70-100' '8-13' '7-12']

Diet ['Insectivore' 'Herbivore' 'Carnivore' 'Omnivore' 'Carnivore, Piscivore'
 'Omnivore, Insectivore' 'Herbivore, Omnivore' 'Filter Feeder' 'Piscivore'
 'Insectivore, Herbivore' 'Scavenger' 'Carnivore, Scavenger'
 'Nectar, Insects' 'Carnivore, Insectivore' 'Omnivore, Herbivore'
 'Herbivore, Insectivore']

Habitat ['Savannas, Grasslands' 'Grasslands, Savannas' 'Savannah, Forest'
 'Savannahs' 'Mountains, Alpine' 'Amazon Rainforest' 'Grasslands, Plains'
 'Grasslands, Forests' 'Middle East, North Africa' 'Desert' 'Tundra'
 'Freshwater Rivers, Lakes' 'North Atlantic, Arctic'
 'Oceans, Coastal Areas' 'Coastal Waters' 'Lakes, Canals' 'Rainforests'
 'Rainforests, Grasslands' 'Forests, Lakes, Coasts' 'Forests'
 'Forests, Mountains' 'Oceans' 'Deserts, Woodlands' 'Grasslands'
 'Grasslands, Mangroves' 'Deep-sea' 'Forests, Urban Areas' 'Coastal Areas'
 'Coral Reefs, Tide Pools' 'Human Dwellings' 'Grasslands, Swamps'
 'Freshwater' 'Coral Reefs' 'Deep-sea, Caves' 'Rainforests, Madagascar'
 'Worldwide' 'Forests, Grasslands' 'Coastal Waters, Seagrass'
 'Amazon Basin' 'Antarctic' 'Gardens, Grasslands' 'Sahara Desert'
 'Forests, Caves' 'Northern Australia' 'Galápagos Islands' nan
 'Savannas, Scrublands' 'Rivers, Lakes' 'Ocean Floor'
 'Temperate Broadleaf Forests' 'Deserts, Scrubland' 'Tropical Rainforests'
 'Swamps, Marshes' 'Ocean Floor, Deep-sea' 'Arctic, Atlantic Ocean'
 'Ocean Floor, Coastal Areas' 'Americas' 'Mediterranean Scrublands'
 'Forests, Islands' 'Deserts' 'Islands, Grasslands' 'Seaweed Beds'
 'Western Ghats, India' 'Rivers, Coastal Areas' 'Mountains' 'Arid regions'
 'Various' 'Rainforests, Mountains' 'Underground Tunnels' 'Arctic Waters'
 'Oceans, Coral Reefs' 'Eucalyptus Forests' 'Central Africa'
 'Eastern Australia' 'Arctic' 'Forests, Woodlands'
 'Mangroves, Rainforests' 'Tropical and Subtropical' 'Scrublands, Forests'
 'Himalayan Foothills' 'Grasslands, Wetlands' 'Cold Regions'
 'Mountains, Steppes' 'Arctic, North America' 'Grasslands, Savannahs'
 'Wetlands, Forests' 'Tropical Forests' 'Australia' 'Desert, Scrublands'
 'Wetlands' 'Islands, Coastal Areas' 'Caves, Forests' 'Gulf of California'
 'Arctic, Coastal Areas' 'Savannahs, Grasslands' 'Boreal Forests, Tundra'
 'Hydrothermal Vents']

Predators ['Lions, Hyenas' 'Lions, Leopards' 'Hyenas, Crocodiles'
 'Wolves, Golden Eagles' 'Birds, Snakes' 'Wolves, Grizzly Bears'
 'Jaguars, Pumas' 'Humans, Predators' 'Polar Bears' 'Birds, Larger Fish'
 'Tigers, Leopards' 'Gulls, Birds of Prey' 'Sharks, Orcas' 'Fish, Birds'
 'Birds of Prey' 'Jaguars, Crocodiles' 'Wolves, Raccoons'
 'Leopards, Eagles' 'Orcas, Great White Sharks' 'Wolves, Birds of Prey'
 'Humans, Crocodiles' nan 'Birds of Prey, Snakes' 'Birds, Bats' 'Orcas'
 'Orcas, Sharks' 'Larger Fish' 'Leopards, Humans' 'Tigers, Humans'
 'Birds, Mammals' 'Wolves, Tigers' 'Leopards, Hawksbills'
 'Jaguars, Anacondas' 'Fish, Crustaceans' 'Larger Fish, Anemones'
 'Sharks, Humans' 'Birds, Raccoons' 'Fossa, Hawks' 'Humans, Dingoes'
 'Dingoes, Eagles' 'Crocodiles, Jaguars' 'Leopard Seals' 'Snakes, Hawks'
 'Foxes, Badgers' 'Eagles, Jackals' 'Birds, Foxes'
 'Humans, Larger Predators' 'Birds, Dingoes' 'Sharks, Birds'
 'Humans, Rats' 'Crocodiles, Tigers' 'Fish, Sharks' 'Snow Leopards'
 'Birds of Prey, Coyotes' 'Larger Fish, Other Sharks' 'Snakes'
 'Jaguars, Caymans' 'Predatory Fish' 'Various Predators'
 'Polar Bears, Orcas' 'Jaguars, Snakes' 'Lions, Crocodiles'
 'Birds, Predatory Fish' 'Humans, Wildcats' 'Fossa, Birds of Prey'
 'Birds, Bees' 'Humans, Leopards' 'Rats, Cats' 'Snakes, Birds of Prey'
 'Stoats, Cats' 'Fish, Octopuses' 'Fossa' 'Birds of Prey, Dingoes'
 'Mongooses, Birds' 'Alligators, Sharks' 'Wolves, Snow Leopards'
 'Snakes, Humans' 'Sea Anemones, Predatory Fish' 'Foxes, Cats'
 'Leopards, Lions' 'Lions, Tigers' 'Foxes, Birds of Prey' 'Birds, Canids'
 'Birds, Spiders' 'Clouded Leopards' 'Coyotes, Bobcats' 'Wolves, Eagles'
 'Snow Leopards, Martens' 'Snakes, Birds' 'Wolves, Coyotes'
 'Snakes, Lizards' 'Leopards, Hyenas' 'Crocodiles, Snakes' 'Larger Sharks'
 'Wolves, Bears' 'Jaguars, Harpy Eagles' 'Humans, Wolves' 'Foxes, Wolves'
 'Tasmanian Tigers' 'Harpy Eagles' 'Fish, Crocodiles'
 'Birds of Prey, Jaguars' 'Quolls, Pythons' 'Eagles, Falcons'
 'Hawks, Owls' 'Nets, Sharks' 'Tigers, Crocodiles' 'Bears, Humans'
 'Bears, Wolves' 'Dingoes, Tasmanian Devils' 'Snow Leopards, Wolves'
 'Seals, Orcas']

Average Speed (km/h) ['40' '24-30' '25' '58' '56' '56-64' '0.1-1' '40-56' '24' '65' '55' '60'
 '16-32' '30-50' '40-64' '24-40' '0.8' '32' '48' '120' '16' '30' '14-28'
 nan '25-35' '40-60' '37' '64' '1.6-2.4' '30-35' '112' '8' '1.6' '30-45'
 '40-45' '48-64' '10-15' '16-56' '2-2.5' '4-6' '40-50' '45-48' '29'
 '24-35' '6-7' '0.3-0.5' '30-40' '1-2' '1.6-3' '8-13' '0.3'
 '16-24 (in water)' '1.6-3.2' '35' '19-22' '50' '0.8-1.6' '40-80' '24-27'
 '70-80' '40-58' '2.5' '20' '6.4-9.6' '0.8-1' '24-29' '0.02-0.03'
 '0.03-0.08' '45' '6-12' '72' '3-7' '16-24' '0.5-0.7' '24-32' '88.5'
 '0.2-0.4' '26' '44' '14-16' '50-65' '0.03-0.24' '80' '1.2' '32-56'
 '40-72' '0.16-0.32' '28' '27' '29-42' '0.03' '17' '70' '22' '47' '56-70']

Countries Found ['Africa' 'Eastern and Southern Africa' 'Sub-Saharan Africa'
 'European Alps' 'Amazon Rainforest' 'North America'
 'Central and South America' 'Middle East, North Africa' 'Middle East'
 'Arctic regions' 'South America, Asia' 'Asia (Southeast)'
 'North Atlantic, Arctic' 'Worldwide' 'Australia, New Zealand' 'Mexico'
 'Madagascar' 'Southeast Asia, South Asia'
 'Gibraltar, North Africa, Middle East' 'Australia' 'India, Nepal, Bhutan'
 'India, Bangladesh, Nepal' 'Australia, New Zealand, Tasmania'
 'Deep-sea regions' 'Oceans worldwide'
 'Eastern Pacific (GalÃ¡pagos Islands)' 'Indo-Pacific region'
 'Democratic Republic of Congo' 'Borneo' 'South and Central America'
 'North America, Europe, Asia' 'Southeast Asia, South Asia, Indonesia'
 'South America' 'Africa, Iran, India' 'Central and West Africa' 'China'
 'Indian, Pacific Oceans' 'Western Indian Ocean' 'Asia'
 'Indian Ocean, Western Pacific' 'Australia, New Guinea' 'Amazon Basin'
 'Antarctica' 'Europe, Asia' 'North Africa' 'Europe' 'Asia, Australia'
 'Northern Australia' 'GalÃ¡pagos Islands' 'Galápagos Islands'
 'Eastern Africa, Horn of Africa' 'Indian subcontinent' 'Pacific Ocean'
 'Southwestern United States, Mexico' 'Brazil, Southeastern Bahia'
 'Western Colombia' 'Eastern Africa' 'Arctic, Atlantic Ocean'
 'Atlantic Ocean, Gulf of Mexico' 'Americas' 'Spain, Portugal'
 'Japan, China, Southeast Asia' 'Japan, China, North Korea' 'New Zealand'
 'Indonesia' 'Southern Australia' 'India' 'Southeast Asia'
 'North, Central, and South America' 'Central Africa'
 'Central Asia, South Asia, Middle East' 'Kalahari Desert, Africa'
 'Africa, Asia, Australia, Oceania' 'Democratic Republic of Congo, Uganda'
 'East Africa' 'Arctic' 'Western Australia' 'Indonesia, Malaysia'
 'Asia, Africa' 'Argentina, Chile' 'Argentina' 'Borneo, Malaysia'
 'China, Nepal, Bhutan, India' 'Central America' 'Vietnam, Laos'
 'Tropical Central Tropical Africa' 'Siberia, Alaska'
 'Central and South Asia' 'Arctic, North America' 'Sumatra'
 'Southeast Asia, Philippines' 'Tasmania, Australia' 'Asia, Tibet'
 'Asia, Russia' 'Papua New Guinea, Indonesia' 'North Pacific'
 'Gulf of California, Mexico' 'Africa, Asia, Americas' 'Arctic, Subarctic'
 'India, Southeast Asia' 'Eurasia, North Africa, Americas'
 'Eurasia, North America, North Africa' 'Northern Hemisphere'
 'Himalayas, Central Asia']

Conservation Status ['Least Concern' 'Vulnerable' 'Endangered' 'Not Evaluated'
 'Near Threatened' nan 'Critically Endangered' 'Data Deficient' 'Extinct'
 'Extinct (around 58 million years ago)'
 'Extinct (around 4,000 years ago)']

Family ['Orycteropodidae' 'Hyaenidae' 'Elephantidae' 'Felidae' 'Canidae'
 'Bovidae' 'Dendrobatidae' 'Myrmecophagidae' 'Equidae' 'Osteoglossidae'
 'Alcidae' 'Delphinidae' 'Otariidae' 'Ambystomatidae' 'Daubentoniidae'
 'Tapiridae' 'Accipitridae' 'Viverridae' 'Cercopithecidae' 'Cetorhinidae'
 'Agamidae' 'Rhinocerotidae' 'Psychrolutidae' 'Corvidae' 'Nymphalidae'
 'Balaenopteridae' 'Sulidae' 'Octopodidae' 'Hominidae' 'Ctenidae'
 'Ursidae' 'Pythonidae' 'Caviidae' 'Cryptobranchidae' 'Pomacentridae'
 'Latimeriidae' 'Chelydridae' 'Indriidae' 'Dugongidae' 'Tachyglossidae'
 'Gymnotidae' 'Spheniscidae' 'Callitrichidae' 'Erinaceidae'
 'Salamandridae' 'Pteropodidae' 'Eupleridae' 'Testudinidae' 'Phasianidae'
 'Gavialidae' 'Enteroctopodidae' 'Helodermatidae' 'Centrolenidae'
 'Mitsukurinidae' 'Lamnidae' 'Boidae' 'Cheloniidae' 'Myxinidae' 'Phocidae'
 'Hippopotamidae' 'Limulidae' 'Trochilidae' 'Indridae' 'Vespidae'
 'Strigopidae' 'Heteromyidae' 'Elapidae' 'Apterygidae' 'Varanidae'
 'Gekkonidae' 'Syngnathidae' 'Lemuridae' 'Menuridae' 'Trichechidae'
 'Stomatopoda' 'Herpestidae' 'Heterocephalidae' 'Monodontidae'
 'Nudibranchia' 'Myrmecobiidae' 'Giraffidae' 'Manidae' 'Gonodactylidae'
 'Chlamyphoridae' 'Dasypodidae' 'Ornithorhynchidae' 'Nyctibiidae'
 'Mantidae' 'Antilocapridae' 'Tetraodontidae' 'Macropodidae' 'Ailuridae'
 'Hylidae' 'Sagittariidae' 'Balaenicipitidae' 'Bradypodidae' 'Lorisidae'
 'Strigidae' 'Physeteridae' 'Atelidae' 'Cebidae' 'Talpidae' 'Tarsiidae'
 'Dasyuridae' 'Thylacinidae' 'Termitoidae' 'Ramphastidae' 'Glossinidae'
 'Rhynchocephalia' 'Pitheciidae' 'Phyllostomidae' 'Phocoenidae'
 'Odobenidae' 'Suidae' 'Rhincodontidae' 'Mustelidae' 'Vombatidae'
 'Picidae' 'Kiwaidae' 'Stegostomatidae']

Gestation Period (days) ['210-240' '90' '640-660' '98-105' '70' '150' '10-15' '270-290' '190-210'
 '330-342' '52-60' nan '40' '360-380' '300-350' '14-21' '160-170'
 '390-395' '34-36' '60-64' '165-200' '36-42 months' '40-70' '50-60'
 '104-106' '450-480' '17-18' '10-12 months' '41-45' '50-70' '220-230'
 '230-270' '12 months' '63' '21-35' '180-250' '88-100' '90-98' '230-240'
 '6-10' '260-330 million years' '40-80' '140-160' '60-63' '13-14 months'
 '255-270' '22-28' '10 weeks' '62-66' '140-145' '35' '50-52' '30-60'
 '140-150' '43-49' '38-40' '135' '275-280' '170-215' '94-123' '95-160'
 '120-150' '10-20' '125-130' '14' '12-18 months' '12-18' '150-160' '45-70'
 '45-75' '390-396' '335' '56-58' '230-250' '2 weeks' '13-22' '365' '63-67'
 '120-140' '1 week' '173-194' '21-24' '22-24' '90-113' '63-92'
 '7-8 months' '45-60' '30-40' '134-138' '120-135' '150-170' '50-55'
 '180-270' '365-450' '175-190' '65-70' '20-30' '135-170' '70-73'
 '14-16 months' '440-450' '420-450' '240-260' '75-80' '6-9 weeks'
 '10 days (in burrow)' '195-265' '10-60' '166-200' '240' '25-30' '52'
 '30-34' '112-158' '5-7' '61-65' '42-46' '54-72' '30-35' '20-24' '120-180'
 '23-26' '90-100' '32-34' '200-294' '110-160' '90-110' '15-20' '16-22'
 '430-640' '425-475' '140-230' '90-150' '180-210' '21-28' '121-128'
 '58-82' '280-310' '420-470' '17-20' '126-130' '12-15' '122-130' '120-130'
 '10-11 months' '20-25' '160-220' '240-270' '220-270' '100-150' '240-300'
 '230-260' '160-190' '90-160' '40-45' '126-138' '215-280' '80-90'
 '180-365' '10-25']

Top Speed (km/h) ['40' '80' '56' '56-64' '0.8' '24' '65' '55' '60' '32' '40-64' '24-40'
 '0.2-0.3' '48' '120' '16' '30' '14-28' nan '39' '25-35' '40-60' '64'
 '1.6-2.4' '35' '112' '1.6' '37' '48-64' '27' '16-56' '4.8' '9' '4-6'
 '40-50' '45-48' '29' '24-35' '0.3' '30-40' '95' '8-13' '28' '50' '24-27'
 '70-80' '2.4' '20' '8' '30-50' '45' '58' '72' '16-24' '24-32' '88.5'
 '0.2-0.4' '26' '44' '14-16' '0.03-0.24' '1.2' '32-56' '40-72' '17' '70'
 '22' '47' '56-70' '25']

Social Structure ['Solitary' 'Herd-based' 'Group-based' 'Colony-based' 'Flocks'
 'Social groups' 'Social pods' 'Pack-based' nan 'Eusocial']

Offspring per Birth ['1' '2-5' '2-4 (usually)' '10-12' 'Up to 40' '4-11' nan '100-300' '1-3'
 '2-4' 'Up to 24' '2-6' '1 (rarely 2)' 'Up to 100' '3-8' 'Up to 1,000'
 '1-4' '30-80' '2-8' '3-5' '20-30' '6-9' '4-8' '1-10' 'Thousands' '1-2'
 '3-7' '10-60' '6-25' 'Up to 16' '20-95' 'Up to 200,000' 'Up to 30'
 '2-14 (approx.)' '2-17' 'Up to 80' '1-4 (usually 1)' '20-40' '20-25'
 'Up to 300' '8-16' 'Hundreds' 'Up to 28' '4-6' 'Up to 10,000'
 '1-3 (rarely 5)' 'Up to 400' '6-12' '2' 'Up to 10' '1-5' '3-11' '40-50'
 '2-10' '1-4 (usually 2-3)' '1-6' 'Up to 200' '4-32' '30-500' '1-14'
 '6-30' '1-1000' '2-20' '2-3' '10-50' '5-20' 'Up to 25']

Additionally, there are some incorrect data entries that need to be addressed later. For example, this fish has a gestation period of 300 million years!

In [8]:
df[df['Animal'] == 'Coelacanth']

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
47,Coelacanth,Up to 200,Up to 90,"Brown, Grey",Up to 60,Carnivore,"Deep-sea, Caves","Sharks, Humans",1.6,Western Indian Ocean,Not Evaluated,Latimeriidae,260-330 million years,NaN,Solitary,NaN

## Data cleaning

### Duplicates values

First, let's address duplicate data by retaining entries with fewer NaN values.

In [9]:
df['NAN sum' ] = df.isna().sum(axis=1)

df = df.sort_values(by=['Animal', 'NAN sum'])
df = df.drop_duplicates(subset=['Animal'], keep='first')
df = df.drop(columns=['NAN sum']).reset_index(drop=True)

In [10]:
df.isnull().sum()

Animal                      0
Height (cm)                 2
Weight (kg)                 2
Color                       4
Lifespan (years)            6
Diet                        0
Habitat                     1
Predators                  11
Average Speed (km/h)       21
Countries Found             0
Conservation Status        12
Family                      0
Gestation Period (days)    16
Top Speed (km/h)           33
Social Structure            1
Offspring per Birth        21
dtype: int64

Next, we'll drop rows where more than 30 percent of the data is missing.

In [11]:
nan_percentage = df.isna().mean(axis=1) * 100

threshold = 30.0
rows_to_drop = df[nan_percentage > threshold]

df = df.drop(rows_to_drop.index)

Average speed and top speed are strongly correlated; therefore, to simplify our analysis, we will fill missing values in the average speed data using the top speed values and subsequently drop the top speed column.

In [12]:
df['Average Speed (km/h)'] = df['Average Speed (km/h)'].fillna(df['Top Speed (km/h)'])
df = df.drop(columns=['Top Speed (km/h)'])
df['Average Speed (km/h)'] = df['Average Speed (km/h)'].replace('Varies', np.nan)

### Target data

In the target column ('Diet'), there are 16 unique values, which we have consolidated into three main categories: Omnivore, Carnivore, and Herbivore.

In [13]:
df['Diet'].value_counts()

Diet
Carnivore                 64
Herbivore                 49
Omnivore                  37
Insectivore               15
Carnivore, Scavenger       4
Carnivore, Insectivore     4
Carnivore, Piscivore       3
Omnivore, Insectivore      2
Filter Feeder              2
Herbivore, Omnivore        1
Piscivore                  1
Insectivore, Herbivore     1
Scavenger                  1
Nectar, Insects            1
Omnivore, Herbivore        1
Herbivore, Insectivore     1
Name: count, dtype: int64

In [14]:
def map_diet(diet):
    diet = diet.lower()
    if 'omnivore' in diet or 'nectar, insects' in diet:
        return 'Omnivore'
    elif 'carnivore' in diet or 'piscivore' in diet or 'scavenger' in diet or 'insectivore' in diet:
        return 'Carnivore'
    elif 'herbivore' in diet or 'filter feeder' in diet:
        return 'Herbivore'
    
    else:
        return diet
    
df['Diet'] = df['Diet'].apply(map_diet)

In [15]:
df['Diet'].value_counts()

Diet
Carnivore    94
Herbivore    51
Omnivore     42
Name: count, dtype: int64

Let's examine the missing values after these changes.

In [16]:
df.isna().sum()

Animal                      0
Height (cm)                 0
Weight (kg)                 0
Color                       0
Lifespan (years)            0
Diet                        0
Habitat                     0
Predators                   4
Average Speed (km/h)       11
Countries Found             0
Conservation Status         6
Family                      0
Gestation Period (days)     7
Social Structure            0
Offspring per Birth        12
dtype: int64

### Missing values

Considering that this dataset pertains to animals, which is common knowledge, we can employ imputation techniques to fill missing values. Neglecting to do so would result in a loss of nearly 20% of the dataset.\
Here, we utilize ChatGPT for missing value imputation in the dataset.

#### Managing missing values in the "Conservation Status" column

In [17]:
df[df['Conservation Status'].isna()]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
9,Arabian Horse,140-160,380-1000,Various,25-30,Herbivore,"Middle East, North Africa","Humans, Predators",65,"Middle East, North Africa",NaN,Equidae,330-342,Herd-based,1
37,Boxer Dog,53-63,25-32,"Fawn, Brindle",10-12,Omnivore,Human Dwellings,NaN,64,Worldwide,NaN,Canidae,63,Social groups,3-8
50,Dalmatian Dog,50-61,23-32,"White, Black",10-13,Omnivore,Worldwide,"Wolves, Birds of Prey",40-45,Worldwide,NaN,Canidae,63,Pack-based,6-9
135,Rottweiler,56-69,36-60,"Black, Tan",8-10,Carnivore,Worldwide,"Wolves, Coyotes",35,Worldwide,NaN,Canidae,61-65,Pack-based,6-12
141,Siberian Husky,50-60,16-27,Various,12-14,Carnivore,Cold Regions,"Wolves, Bears",50-65,"Siberia, Alaska",NaN,Canidae,60-63,Pack-based,4-6
164,Tibetan Mastiff,61-78,63-75,"Black, Brown, Gray",10-12,Omnivore,Human Dwellings,NaN,45,"Asia, Tibet",NaN,Canidae,58-82,Social groups,1-10

In [18]:
conservation_status = {
    'Arabian Horse' : 'Least Concern',
    'Boxer Dog' : 'Not Evaluated',
    'Dalmatian Dog' : 'Not Evaluated',
    'Rottweiler' : 'Least Concern',
    'Siberian Husky' : 'Least Concern',
    'Tibetan Mastiff' : 'Least Concern'
}
df.loc[df['Animal'].isin(conservation_status.keys()), 'Conservation Status']= df['Animal'].replace(conservation_status)

#### Managing missing values in the "Offspring per Birth" column

In [19]:
df[df['Offspring per Birth'].isna()]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
12,Arowana,Up to 120,Up to 6.7,"Silver, Gold, Green",10-20,Carnivore,"Freshwater Rivers, Lakes","Birds, Larger Fish",16-32,"South America, Asia",Not Evaluated,Osteoglossidae,NaN,Solitary,NaN
30,Blue Morpho Butterfly,Up to 15,Up to 0.028,Blue,1-2 weeks,Herbivore,Rainforests,"Birds, Bats",NaN,Central and South America,Not Evaluated,Nymphalidae,NaN,Solitary,NaN
44,Chinese Giant Salamander,Up to 180,Up to 65,Dark Brown,Up to 70,Carnivore,Freshwater,"Fish, Crustaceans",NaN,China,Critically Endangered,Cryptobranchidae,50-60,Solitary,NaN
46,Coelacanth,Up to 200,Up to 90,"Brown, Grey",Up to 60,Carnivore,"Deep-sea, Caves","Sharks, Humans",1.6,Western Indian Ocean,Not Evaluated,Latimeriidae,260-330 million years,Solitary,NaN
74,Gila Monster,Up to 60,Up to 2.3,"Black, Orange",Up to 20,Carnivore,"Deserts, Scrubland","Birds of Prey, Coyotes",1-2,"Southwestern United States, Mexico",Least Concern,Helodermatidae,120-150,Solitary,NaN
76,Goblin Shark,Up to 320,Up to 210,Pinkish-gray,30-35,Carnivore,Deep-sea,"Larger Fish, Other Sharks",1.6-3,Worldwide,Data Deficient,Mitsukurinidae,NaN,Solitary,NaN
81,Green Sea Turtle,Up to 120,Up to 200,Greenish-brown,80-100,Herbivore,"Oceans, Coastal Areas",Predatory Fish,1.6-3.2,Oceans worldwide,Endangered,Cheloniidae,45-70,Solitary,NaN
83,Hagfish,Up to 127,Up to 0.7,"Pink, Gray",Up to 300,Carnivore,"Ocean Floor, Deep-sea",Various Predators,0.8,Oceans worldwide,Least Concern,Myxinidae,NaN,Solitary,NaN
115,Nudibranch,Up to 30,Up to 1,Various,Up to 10,Carnivore,"Oceans, Coral Reefs","Sea Anemones, Predatory Fish",NaN,Oceans worldwide,Not Evaluated,Nudibranchia,NaN,Solitary,NaN
129,Pufferfish,Up to 60,Up to 0.8,Various,3-10,Carnivore,Tropical and Subtropical,"Sharks, Humans",8,Oceans worldwide,Not Evaluated,Tetraodontidae,NaN,Solitary,NaN
162,Thorny Devil,Up to 20,Up to 85,"Brown, Tan",5-20,Carnivore,"Desert, Scrublands","Birds, Snakes",0.16-0.32,Australia,Least Concern,Agamidae,NaN,Solitary,NaN
166,Titanoboa,Up to 1440,Up to 24950,Dark Brown,10-15,Carnivore,Wetlands,"Fish, Crocodiles",27,South America,Extinct (around 58 million years ago),Boidae,420-470,Solitary,NaN

In [20]:
offspring_per_birth = {
    'Arowana' : '20-30',
    'Blue Morpho Butterfly' : '100-200',
    'Blobfish' : 'Thousands',
    'Chinese Giant Salamander' : '400-500',
    'Coelacanth' : '26-28',
    'Gila Monster' : '3-13',
    'Goblin Shark' :  '1-3',
    'Green Sea Turtle' : '100-200',
    'Hagfish' : '30-50',
    'Nudibranch' : 'Thousands',
    'Pufferfish' : 'Thousands',
    'Thorny Devil' : '3-10',
    'Titanoboa' : 'Hundreds',
    'Yeti Crab' : '10-12',
}
df.loc[df['Animal'].isin(offspring_per_birth.keys()), 'Offspring per Birth']= df['Animal'].replace(offspring_per_birth)

#### Managing missing values in the "Gestation Period (days)" column

In [21]:
df[df['Gestation Period (days)'].isna()]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
12,Arowana,Up to 120,Up to 6.7,"Silver, Gold, Green",10-20,Carnivore,"Freshwater Rivers, Lakes","Birds, Larger Fish",16-32,"South America, Asia",Not Evaluated,Osteoglossidae,NaN,Solitary,20-30
30,Blue Morpho Butterfly,Up to 15,Up to 0.028,Blue,1-2 weeks,Herbivore,Rainforests,"Birds, Bats",NaN,Central and South America,Not Evaluated,Nymphalidae,NaN,Solitary,100-200
76,Goblin Shark,Up to 320,Up to 210,Pinkish-gray,30-35,Carnivore,Deep-sea,"Larger Fish, Other Sharks",1.6-3,Worldwide,Data Deficient,Mitsukurinidae,NaN,Solitary,1-3
83,Hagfish,Up to 127,Up to 0.7,"Pink, Gray",Up to 300,Carnivore,"Ocean Floor, Deep-sea",Various Predators,0.8,Oceans worldwide,Least Concern,Myxinidae,NaN,Solitary,30-50
115,Nudibranch,Up to 30,Up to 1,Various,Up to 10,Carnivore,"Oceans, Coral Reefs","Sea Anemones, Predatory Fish",NaN,Oceans worldwide,Not Evaluated,Nudibranchia,NaN,Solitary,Thousands
129,Pufferfish,Up to 60,Up to 0.8,Various,3-10,Carnivore,Tropical and Subtropical,"Sharks, Humans",8,Oceans worldwide,Not Evaluated,Tetraodontidae,NaN,Solitary,Thousands
162,Thorny Devil,Up to 20,Up to 85,"Brown, Tan",5-20,Carnivore,"Desert, Scrublands","Birds, Snakes",0.16-0.32,Australia,Least Concern,Agamidae,NaN,Solitary,3-10

In [22]:
gestation_period = {
    'Arowana' : '50-60',
    'Blue Morpho Butterfly' : '9-14',
    'Blobfish' : '9 months',
    'Goblin Shark' : '12 months',
    'Hagfish' : '11 months',
    'Nudibranch' : '1-2 weeks',
    'Pufferfish' :  '7-10',
    'Thorny Devil' : '90-120',
    'Yeti Crab' : '210-270'
}
df.loc[df['Animal'].isin(gestation_period.keys()), 'Gestation Period (days)']= df['Animal'].replace(gestation_period)

#### Managing missing values in the "Average Speed (km/h)" column

In [23]:
df[df['Average Speed (km/h)'].isna()]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
30,Blue Morpho Butterfly,Up to 15,Up to 0.028,Blue,1-2 weeks,Herbivore,Rainforests,"Birds, Bats",NaN,Central and South America,Not Evaluated,Nymphalidae,9-14,Solitary,100-200
33,Blue-Ringed Octopus,Up to 20,Up to 0.3,"Blue, Brown",6-8 months,Carnivore,"Coral Reefs, Tide Pools",Larger Fish,NaN,Indo-Pacific region,Near Threatened,Octopodidae,50-70,Solitary,Up to 100
38,Brazilian Wandering Spider,Up to 5,Up to 0.006,Brown,1-2,Carnivore,Forests,"Birds, Mammals",NaN,South and Central America,Not Evaluated,Ctenidae,21-35,Solitary,"Up to 1,000"
44,Chinese Giant Salamander,Up to 180,Up to 65,Dark Brown,Up to 70,Carnivore,Freshwater,"Fish, Crustaceans",NaN,China,Critically Endangered,Cryptobranchidae,50-60,Solitary,400-500
48,Common Snapping Turtle,20-36,4.5-16,"Brown, Gray",30-50,Omnivore,Freshwater,"Birds, Raccoons",NaN,North America,Least Concern,Chelydridae,40-80,Solitary,20-30
100,Leafy Sea Dragon,Up to 35,Up to 0.5,"Brown, Green",Up to 10,Carnivore,Seaweed Beds,"Fish, Octopuses",NaN,Southern Australia,Near Threatened,Syngnathidae,30-40,Solitary,Up to 300
104,Malayan Krait,Up to 150,Up to 2.2,"Black, Yellow",10-15,Carnivore,"Forests, Grasslands","Mongooses, Birds",NaN,Southeast Asia,Least Concern,Elapidae,180-270,Solitary,8-16
115,Nudibranch,Up to 30,Up to 1,Various,Up to 10,Carnivore,"Oceans, Coral Reefs","Sea Anemones, Predatory Fish",NaN,Oceans worldwide,Not Evaluated,Nudibranchia,1-2 weeks,Solitary,Thousands
134,Red-Eyed Tree Frog,5.1-7.5,Up to 0.1,"Green, Red",Up to 5,Carnivore,Rainforests,"Snakes, Birds",NaN,Central America,Least Concern,Hylidae,5-7,Solitary,Up to 100
143,Slow Loris,20-38,0.3-1.6,Yellowish-Brown,20-24,Omnivore,Forests,"Birds, Snakes",NaN,Southeast Asia,Vulnerable,Lorisidae,23-26,Solitary,Up to 10
174,Vaquita,Up to 150,Up to 55,"Grey, White",20-21,Carnivore,Gulf of California,"Nets, Sharks",NaN,"Gulf of California, Mexico",Critically Endangered,Phocoenidae,10-11 months,Solitary,1

In [24]:
avg_speed = {
    'Blobfish' : 0.1,
    'Blue Morpho Butterfly' : 13,
    'Blue-Ringed Octopus' : 8.0,
    'Brazilian Wandering Spider' : 1.5,
    'Chinese Giant Salamander' : 3.0,
    'Common Snapping Turtle' : 4.0,
    'Leafy Sea Dragon' :  5.6,
    'Malayan Krait' : 1.2,
    'Nudibranch' : 0.2,
    'Red-Eyed Tree Frog' : 16,
    'Slow Loris' : 4.3,
    'Vaquita' : 5.1,
    'Yeti Crab' : 0.006
}
df.loc[df['Animal'].isin(avg_speed.keys()), 'Average Speed (km/h)']= df['Animal'].replace(avg_speed)

#### Managing missing values in the "Predators" column

In [25]:
df[df['Predators'].isna()]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
37,Boxer Dog,53-63,25-32,"Fawn, Brindle",10-12,Omnivore,Human Dwellings,NaN,64,Worldwide,Not Evaluated,Canidae,63,Social groups,3-8
151,Star-Nosed Mole,12-20,Up to 0.06,"Black, Pink",Up to 4,Carnivore,"Wetlands, Forests",NaN,1.2,North America,Least Concern,Talpidae,16-22,Solitary,2-10
164,Tibetan Mastiff,61-78,63-75,"Black, Brown, Gray",10-12,Omnivore,Human Dwellings,NaN,45,"Asia, Tibet",Least Concern,Canidae,58-82,Social groups,1-10
181,Whale Shark,Up to 1800,Up to 1500,"Gray, White",70-100,Herbivore,Oceans,NaN,70,Worldwide,Endangered,Rhincodontidae,100-150,Solitary,1

In [26]:
predators = {
    'Blobfish' : 'Sharks, Deep-sea fish',
    'Boxer Dog' : 'Coyotes, Wolves',
    'Star-Nosed Mole' : 'Owls, Hawks, Foxes, Weasels',
    'Tibetan Mastiff' : 'Wolves, Bears',
    'Whale Shark' : 'Orcas, Larger Sharks',
    'Yeti Crab' : 'Octopuses, Fish'
}
df.loc[df['Animal'].isin(predators.keys()), 'Predators']= df['Animal'].replace(predators)

Now that missing values have been addressed, there remain some incorrect values.

In [27]:
df.isna().sum()

Animal                     0
Height (cm)                0
Weight (kg)                0
Color                      0
Lifespan (years)           0
Diet                       0
Habitat                    0
Predators                  0
Average Speed (km/h)       0
Countries Found            0
Conservation Status        0
Family                     0
Gestation Period (days)    0
Social Structure           0
Offspring per Birth        0
dtype: int64

### Incorrect values

Let's preprocess the data by removing prefixes such as 'Ups to' and 'usully', and converting string values to numerical by averaging the data.

In [28]:
def process_range(range_str):
    multi = 1
    if type(range_str) is float or type(range_str) is int:
        return range_str
    elif range_str == '6-8 months':
        return 7/12
    elif range_str == '1-2 weeks':
        return 2 / 28
    elif range_str == '260-330 million years':
        return 5
    elif range_str == '1-4 (usually 2-3)':
        return 3
    elif range_str == 'Hundreds':
        return 1e2
    elif range_str == 'Thousands':
        return 1e3
    elif 'months' in range_str:
        multi = 30
    elif 'tons' in range_str:
        multi = 1e3
    elif 'weeks' in range_str:
        multi = 7
    
    
    range_str = re.sub(r'[^0-9\-.]', '', range_str)
    
    if '-' in range_str:
        num1, num2 = map(float, range_str.split('-'))
        return (num1 + num2) / 2
    else:
        return float(range_str) * multi

columns_to_apply =['Height (cm)', 'Weight (kg)', 'Lifespan (years)', 'Average Speed (km/h)', 'Gestation Period (days)', 'Offspring per Birth']
for col in columns_to_apply:
    df[col] = df[col].apply(process_range)

There are other instances of incorrect data that need cleaning, such as this fish with a lifespan of 300 years!

In [29]:
df[df['Lifespan (years)'] > 150]

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
83,Hagfish,127.0,0.7,"Pink, Gray",300.0,Carnivore,"Ocean Floor, Deep-sea",Various Predators,0.8,Oceans worldwide,Least Concern,Myxinidae,330.0,Solitary,40.0

In [30]:
df.loc[df['Animal'] == 'Hagfish', 'Lifespan (years)'] = 40

Some entries in the Predators column contain the label 'Predators' instead of useful data. We need to address and handle these cases as well

In [31]:
for row in df.iterrows():
    if 'Predators' in row[1]['Predators']: 
        print(row)

(9, Animal                                 Arabian Horse
Height (cm)                                    150.0
Weight (kg)                                    690.0
Color                                        Various
Lifespan (years)                                27.5
Diet                                       Herbivore
Habitat                    Middle East, North Africa
Predators                          Humans, Predators
Average Speed (km/h)                            65.0
Countries Found            Middle East, North Africa
Conservation Status                    Least Concern
Family                                       Equidae
Gestation Period (days)                        336.0
Social Structure                          Herd-based
Offspring per Birth                              1.0
Name: 9, dtype: object)
(63, Animal                                        Fossa
Height (cm)                                    80.0
Weight (kg)                                     6.5
Color                          Brown, Reddish-brown
Lifespan (years)                               17.5
Diet                                      Carnivore
Habitat                     Rainforests, Madagascar
Predators                  Humans, Larger Predators
Average Speed (km/h)                           46.5
Countries Found                          Madagascar
Conservation Status                      Vulnerable
Family                                   Eupleridae
Gestation Period (days)                        90.0
Social Structure                           Solitary
Offspring per Birth                             3.0
Name: 63, dtype: object)
(83, Animal                                   Hagfish
Height (cm)                                127.0
Weight (kg)                                  0.7
Color                                 Pink, Gray
Lifespan (years)                            40.0
Diet                                   Carnivore
Habitat                    Ocean Floor, Deep-sea
Predators                      Various Predators
Average Speed (km/h)                         0.8
Countries Found                 Oceans worldwide
Conservation Status                Least Concern
Family                                 Myxinidae
Gestation Period (days)                    330.0
Social Structure                        Solitary
Offspring per Birth                         40.0
Name: 83, dtype: object)
(98, Animal                                Komodo Dragon
Height (cm)                                   300.0
Weight (kg)                                    90.0
Color                                          Grey
Lifespan (years)                               25.0
Diet                                      Carnivore
Habitat                         Islands, Grasslands
Predators                  Humans, Larger Predators
Average Speed (km/h)                           20.0
Countries Found                           Indonesia
Conservation Status                      Vulnerable
Family                                    Varanidae
Gestation Period (days)                         7.5
Social Structure                           Solitary
Offspring per Birth                            22.5
Name: 98, dtype: object)

In [32]:
replace_predators = {
    'Arabian Horse' : 'Humans, Wolves, Bears',
    'Fossa' : 'Crocodiles, Birds of Prey',
    'Hagfish' : 'Larger Fish, Seals, Sharks',
    'Komodo Dragon' : 'Humans, Birds of Prey',
}
df.loc[df['Animal'].isin(replace_predators.keys()), 'Predators']= df['Animal'].replace(replace_predators)

By examining the unique values in the "Habitat" column, it is evident that there are duplicates due to misspellings, such as "deserts" and "desert".

In [33]:
predators = df['Habitat'].str.split(', ', expand=True).stack()
predators_set = predators.unique()
predators_set

array(['Savannas', 'Grasslands', 'Savannah', 'Forest', 'Savannahs',
       'Mountains', 'Alpine', 'Amazon Rainforest', 'Plains', 'Forests',
       'Middle East', 'North Africa', 'Desert', 'Tundra',
       'Freshwater Rivers', 'Lakes', 'North Atlantic', 'Arctic', 'Oceans',
       'Coastal Areas', 'Coastal Waters', 'Canals', 'Rainforests',
       'Coasts', 'Deserts', 'Woodlands', 'Mangroves', 'Urban Areas',
       'Coral Reefs', 'Tide Pools', 'Human Dwellings', 'Swamps',
       'Freshwater', 'Deep-sea', 'Caves', 'Madagascar', 'Worldwide',
       'Seagrass', 'Amazon Basin', 'Antarctic', 'Gardens',
       'Sahara Desert', 'Northern Australia', 'Galápagos Islands',
       'Scrublands', 'Rivers', 'Ocean Floor',
       'Temperate Broadleaf Forests', 'Scrubland', 'Tropical Rainforests',
       'Marshes', 'Atlantic Ocean', 'Americas',
       'Mediterranean Scrublands', 'Islands', 'Seaweed Beds',
       'Western Ghats', 'India', 'Arid regions', 'Underground Tunnels',
       'Arctic Waters', 'Eucalyptus Forests', 'Central Africa',
       'Eastern Australia', 'Tropical and Subtropical',
       'Himalayan Foothills', 'Wetlands', 'Cold Regions', 'Steppes',
       'North America', 'Tropical Forests', 'Australia',
       'Gulf of California', 'Boreal Forests'], dtype=object)

In [34]:
from functools import reduce
replace_habitat = {
'Deserts' : 'Desert',
'Desert' : 'Deserts',
'Forests' : 'Forest',
'Forest' : 'Forests',
'Savannahs' : 'Savannas',
'Savannah' : 'Savannas',
}

df['Habitat'] = df['Habitat'].apply(lambda x: reduce(lambda s, kv: s.replace(*kv), replace_habitat.items(), x))

### Clean dataset
Now that the dataset has been cleaned, let's examine it.

In [35]:
df.head()

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Social Structure,Offspring per Birth
0,Aardvark,117.5,52.5,Grey,25.0,Carnivore,"Savannas, Grasslands","Lions, Hyenas",40.0,Africa,Least Concern,Orycteropodidae,225.0,Solitary,1.0
1,Aardwolf,45.0,11.0,Yellow-brown,11.0,Carnivore,"Grasslands, Savannas","Lions, Leopards",27.0,Eastern and Southern Africa,Least Concern,Hyaenidae,90.0,Solitary,3.5
2,African Elephant,290.0,4350.0,Grey,65.0,Herbivore,"Savannas, Forests","Lions, Hyenas",25.0,Africa,Vulnerable,Elephantidae,650.0,Herd-based,1.0
3,African Lion,95.0,185.0,Tan,12.0,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58.0,Africa,Vulnerable,Felidae,101.5,Group-based,3.0
4,African Wild Dog,77.5,27.0,Multicolored,11.0,Carnivore,Savannas,"Lions, Hyenas",56.0,Sub-Saharan Africa,Endangered,Canidae,70.0,Group-based,11.0

In [36]:
df.isna().sum()

Animal                     0
Height (cm)                0
Weight (kg)                0
Color                      0
Lifespan (years)           0
Diet                       0
Habitat                    0
Predators                  0
Average Speed (km/h)       0
Countries Found            0
Conservation Status        0
Family                     0
Gestation Period (days)    0
Social Structure           0
Offspring per Birth        0
dtype: int64

We lose only 18 rows of data, which is less than 10% of the total dataset; notably, 9 of these are duplicate rows.

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 187 entries, 0 to 195
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   187 non-null    object
 1   Height (cm)              187 non-null    float64
 2   Weight (kg)              187 non-null    float64
 3   Color                    187 non-null    object
 4   Lifespan (years)         187 non-null    float64
 5   Diet                     187 non-null    object
 6   Habitat                  187 non-null    object
 7   Predators                187 non-null    object
 8   Average Speed (km/h)     187 non-null    float64
 9   Countries Found          187 non-null    object
 10  Conservation Status      187 non-null    object
 11  Family                   187 non-null    object
 12  Gestation Period (days)  187 non-null    float64
 13  Social Structure         187 non-null    object
 14  Offspring per Birth      187 non-null    float64
dtypes: float64(6), object(9)
memory usage: 27.4+ KB

In [38]:
df.describe().round(2)

,Height (cm),Weight (kg),Lifespan (years),Average Speed (km/h),Gestation Period (days),Offspring per Birth
count,187.00,187.00,187.00,187.00,187.00,187.00
mean,175.83,1889.82,22.93,31.38,134.83,1182.79
std,373.59,15409.98,18.96,22.36,129.03,14636.52
min,4.50,0.01,0.07,0.02,0.07,1.00
25%,40.00,3.32,11.50,14.00,37.00,1.00
50%,78.50,31.50,17.50,30.00,90.00,2.50
75%,150.00,180.00,27.50,45.75,207.50,15.75
max,3200.00,200000.00,125.00,120.00,650.00,200000.00

Finally, save the final dataset as a CSV file for future tasks.

In [39]:
df.to_csv('data/animal_dataset_processed.csv', index=False)